#!/usr/bin/env sh

DECKY_USER="$1"
DECKY_USER_HOME=$(getent passwd $DECKY_USER | cut -d: -f6)

DECKY_VAR_DATA="$DECKY_USER_HOME/.local/var/opt/decky-loader"
install -d -o $DECKY_USER -g $DECKY_USER "$DECKY_VAR_DATA/services" "$DECKY_VAR_DATA/plugins"

STEAM_DEBUGGING_FILE="$DECKY_USER_HOME/.steam/steam/.cef-enable-remote-debugging"
[ -f "$STEAM_DEBUGGING_FILE" ] || touch "$STEAM_DEBUGGING_FILE"
